apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gerrit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://gerrit.googlesource.com/k8s-gerrit.git
    path: helm-charts/gerrit

    helm:
      parameters:
        - name: "storageClasses.default.name"
          value: "standard"
        - name: "storageClasses.shared.name"
          value: "standard"

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: gerrit

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

  # Will ignore differences between live and desired states during the diff. Note that these configurations are not
  # used during the sync process.
  ignoreDifferences:
    # for the specified json pointers
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    # for the specified managedFields managers
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - kube-controller-manager
